name: "CHANGE ME"  # CHANGE ME
baseurl: /morea-core-custom # CHANGE ME
github_org_url: https://github.com/mbmosman/morea-core # CHANGE ME
github_org_name: "CHANGE ME" # CHANGE ME

# The following properties should not need to change semester to semester.
markdown: kramdown
kramdown:
  hard_wrap: false
  input: GFM
  syntax_highlighter: rouge
mathjax: true
exclude: [morea]
morea_theme: spacelab
morea_navbar_items:
  #- Prerequisites
  - Modules
  - Outcomes
  - Readings
  - Experiences
  - Assessments
  - Schedule

gems:
  - jekyll-gist
  - jemoji

# CHANGE for each course template, but no need to change each semester
morea_course: CHANGE ME
morea_domain: http://changeme.github.io/
morea_google_analytics_tracking_id: "UA-XXXXXXXX-X"
googleCalendarApiKey: changeme
googleCourseCalendarId: 'change-me@group.calendar.google.com'
googleCollegeCalendarId: 'change-me@group.calendar.google.com'
